package codex

import "github.com/MrSFGriffin/GryphDash-Providers/internal/dashboard"

func Catalog() dashboard.WidgetCatalog {
	return dashboard.WidgetCatalog{Widgets: []dashboard.WidgetConfig{
		{ID: "codex/bucket/{bucket}/primary", Group: "Codex", Name: "Primary limit", Description: "Remaining percentage in the primary quota window", Scope: "limitBuckets", Default: true, Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "limitWindow", Path: "primary", Source: "codex/limits"}},
		{ID: "codex/bucket/{bucket}/secondary", Group: "Codex", Name: "Secondary limit", Description: "Remaining percentage in the secondary quota window", Scope: "limitBuckets", Default: true, Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "limitWindow", Path: "secondary", Source: "codex/limits"}},
		{ID: "codex/bucket/{bucket}/credits/balance", Group: "Codex", Name: "Credits remaining", Description: "Spendable credits · not USD", Scope: "limitBuckets", Default: true, Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "credits.balance", Source: "codex/limits"}},
		{ID: "codex/bucket/{bucket}/credits/hasCredits", Group: "Codex", Name: "Credits available", Description: "Whether the account has spendable credits", Scope: "limitBuckets", Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "credits.hasCredits", Source: "codex/limits"}},
		{ID: "codex/bucket/{bucket}/credits/unlimited", Group: "Codex", Name: "Unlimited credits", Description: "Provider-reported credit status", Scope: "limitBuckets", Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "credits.unlimited", Source: "codex/limits"}},
		{ID: "codex/bucket/{bucket}/planType", Group: "Codex", Name: "Bucket plan", Description: "Plan associated with this limit bucket", Scope: "limitBuckets", Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "planType", Source: "codex/limits"}},
		{ID: "codex/bucket/{bucket}/limitName", Group: "Codex", Name: "Limit name", Description: "Optional provider label for this limit bucket", Scope: "limitBuckets", Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "limitName", Source: "codex/limits"}},
		{ID: "codex/bucket/{bucket}/spendControlReached", Group: "Codex", Name: "Spend control reached", Description: "Provider-reported spend-control state", Scope: "limitBuckets", Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "spendControlReached", Source: "codex/limits"}},
		{ID: "codex/bucket/{bucket}/rateLimitReachedType", Group: "Codex", Name: "Reached-limit state", Description: "Provider-reported limit state", Scope: "limitBuckets", Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "rateLimitReachedType", Source: "codex/limits"}},
		{ID: "codex/bucket/{bucket}/individual/limit", Group: "Codex", Name: "Individual spend allowance", Description: "Provider-reported units", Scope: "limitBuckets", Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "individualLimit.limit", Source: "codex/limits"}},
		{ID: "codex/bucket/{bucket}/individual/used", Group: "Codex", Name: "Individual spend used", Description: "Provider-reported units", Scope: "limitBuckets", Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "individualLimit.used", Source: "codex/limits"}},
		{ID: "codex/bucket/{bucket}/individual/remainingPercent", Group: "Codex", Name: "Individual spend remaining", Description: "Provider-reported percent", Scope: "limitBuckets", Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "individualLimit.remainingPercent", Source: "codex/limits"}},
		{ID: "codex/bucket/{bucket}/individual/resetsAt", Group: "Codex", Name: "Individual spend reset", Description: "UTC reset time", Scope: "limitBuckets", Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "timestamp", Path: "individualLimit.resetsAt", Source: "codex/limits"}},
		{ID: "codex/resets/count", Group: "Codex", Name: "Available resets", Description: "Earned resets are separate from spendable credits", Default: true, Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "rateLimitResetCredits.availableCount", Source: "codex/limits"}},
		{ID: "codex/resets/details", Group: "Codex", Name: "Earned reset details", Description: "Read only · the provider may return fewer details than the available count", Width: 8, Height: 6, Logic: dashboard.WidgetLogic{Type: "resetDetails", Path: "rateLimitResetCredits", Source: "codex/limits"}},
		{ID: "codex/usage/lifetimeTokens", Group: "Codex", Name: "Lifetime tokens", Description: "tokens", Default: true, Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "summary.lifetimeTokens", Source: "codex/usage"}},
		{ID: "codex/usage/peakDailyTokens", Group: "Codex", Name: "Peak daily tokens", Description: "tokens", Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "summary.peakDailyTokens", Source: "codex/usage"}},
		{ID: "codex/usage/longestRunningTurnSec", Group: "Codex", Name: "Longest-running turn", Description: "seconds", Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "summary.longestRunningTurnSec", Source: "codex/usage"}},
		{ID: "codex/usage/currentStreakDays", Group: "Codex", Name: "Current streak", Description: "days", Default: true, Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "summary.currentStreakDays", Source: "codex/usage"}},
		{ID: "codex/usage/longestStreakDays", Group: "Codex", Name: "Longest streak", Description: "days", Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "summary.longestStreakDays", Source: "codex/usage"}},
		{ID: "codex/usage/daily", Group: "Codex", Name: "Daily token activity", Description: "Dates as returned by Codex; missing dates are not filled with zero", Default: true, Width: 8, Height: 6, Logic: dashboard.WidgetLogic{Type: "daily", Path: "dailyUsageBuckets", Source: "codex/usage"}},
		{ID: "codex/account/plan", Group: "Codex", Name: "Account plan", Description: "ChatGPT subscription", Default: true, Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "account.planType", Source: "codex/account"}},
		{ID: "codex/account/auth", Group: "Codex", Name: "Authentication", Description: "Local Codex login", Width: 4, Height: 4, Logic: dashboard.WidgetLogic{Type: "scalar", Path: "account.type", Source: "codex/account"}},
	}}
}
